package:
    name: dss_python_backend
    version: "{{ load_setup_py_data().version }}"
    
source:
    #git_rev: "0.10.3"
    #git_url: https://github.com/dss-extensions/dss_python_backend.git
    path: ..
    
build:
    script_env:
        - DSS_CAPI_PATH
        - SDKROOT
requirements:
    build:
        - "{{ compiler('c') }}"
#        - {{ compiler('cxx') }}
        - "python {{ python }}"
        - cffi
        - setuptools
        - wheel
        # - pip
        # - cmake [osx]
        # - git
        
    host:
        - python
        - setuptools
        - cffi
        
    run: 
        - python
        - cffi
        - numpy

