from enum import IntEnum

class Signatures(IntEnum):
    Empty = 0
    Int32 = 1
    String = 2
    Float64 = 3
    Complex128 = 4
    Int8 = 5
    Float32 = 6
    Complex64 = 7
    OneComplex128 = 8

str_funcs = (
    ("ActiveClass_Get_Name", 0),
    ("ActiveClass_Get_ActiveClassName", 0),
    ("ActiveClass_Get_ActiveClassParent", 0),
    ("Bus_Get_Name", 0),
    ("Capacitors_Get_Name", 0),
    ("CapControls_Get_Capacitor", 0),
    ("CapControls_Get_MonitoredObj", 0),
    ("CapControls_Get_Name", 0),
    ("Circuit_Get_Name", 0),
    ("CktElement_Get_Name", 0),
    ("CktElement_Get_DisplayName", 0),
    ("CktElement_Get_GUID", 0),
    ("CktElement_Get_EnergyMeter", 0),
    ("CktElement_Get_VariableName", 0),
    ("DSS_Get_Version", 0),
    ("DSS_Get_DataPath", 0),
    ("DSS_Get_DefaultEditor", 0),
    ("DSSElement_Get_Name", 0),
    ("DSSProperty_Get_Description", 0),
    ("DSSProperty_Get_Name", 0),
    ("DSSProperty_Get_Val", 0),
    ("Error_Get_Description", 0),
    ("Fuses_Get_Name", 0),
    ("Fuses_Get_MonitoredObj", 0),
    ("Fuses_Get_SwitchedObj", 0),
    ("Fuses_Get_TCCcurve", 0),
    ("Generators_Get_Name", 0),
    ("Generators_Get_daily", 0),
    ("Generators_Get_duty", 0),
    ("Generators_Get_Yearly", 0),
    ("Generators_Get_Bus1", 0),
    ("GICSources_Get_Name", 0),
    ("GICSources_Get_Bus1", 0),
    ("GICSources_Get_Bus2", 0),
    ("ISources_Get_Name", 0),
    ("LineCodes_Get_Name", 0),
    ("Lines_Get_Bus1", 0),
    ("Lines_Get_Bus2", 0),
    ("Lines_Get_LineCode", 0),
    ("Lines_Get_Name", 0),
    ("Lines_Get_Geometry", 0),
    ("Lines_Get_Spacing", 0),
    ("Loads_Get_Name", 0),
    ("Loads_Get_CVRcurve", 0),
    ("Loads_Get_daily", 0),
    ("Loads_Get_duty", 0),
    ("Loads_Get_Growth", 0),
    ("Loads_Get_Spectrum", 0),
    ("Loads_Get_Yearly", 0),
    ("Loads_Get_Sensor", 0),
    ("LoadShapes_Get_Name", 0),
    ("Meters_Get_Name", 0),
    ("Meters_Get_MeteredElement", 0),
    ("Monitors_Get_FileName", 0),
    ("Monitors_Get_Name", 0),
    ("Monitors_Get_Element", 0),
    ("Parser_Get_CmdString", 0),
    ("Parser_Get_NextParam", 0),
    ("Parser_Get_StrValue", 0),
    ("Parser_Get_WhiteSpace", 0),
    ("Parser_Get_BeginQuote", 0),
    ("Parser_Get_EndQuote", 0),
    ("Parser_Get_Delimiters", 0),
    ("PDElements_Get_Name", 0),
    ("PVSystems_Get_Name", 0),
    ("PVSystems_Get_daily", 0),
    ("PVSystems_Get_duty", 0),
    ("PVSystems_Get_yearly", 0),
    ("PVSystems_Get_Tdaily", 0),
    ("PVSystems_Get_Tduty", 0),
    ("PVSystems_Get_Tyearly", 0),
    ("PVSystems_Get_Sensor", 0),
    ("Reclosers_Get_Name", 0),
    ("Reclosers_Get_SwitchedObj", 0),
    ("Reclosers_Get_MonitoredObj", 0),
    ("RegControls_Get_MonitoredBus", 0),
    ("RegControls_Get_Name", 0),
    ("RegControls_Get_Transformer", 0),
    ("Relays_Get_Name", 0),
    ("Relays_Get_MonitoredObj", 0),
    ("Relays_Get_SwitchedObj", 0),
    ("Sensors_Get_MeteredElement", 0),
    ("Sensors_Get_Name", 0),
    ("Settings_Get_AutoBusList", 0),
    ("Settings_Get_PriceCurve", 0),
    ("Solution_Get_ModeID", 0),
    ("Solution_Get_LDCurve", 0),
    ("Solution_Get_DefaultDaily", 0),
    ("Solution_Get_DefaultYearly", 0),
    ("SwtControls_Get_Name", 0),
    ("SwtControls_Get_SwitchedObj", 0),
    ("Text_Get_Command", 0),
    ("Text_Get_Result", 0),
    ("Topology_Get_BranchName", 0),
    ("Topology_Get_BusName", 0),
    ("Transformers_Get_Name", 0),
    ("Transformers_Get_XfmrCode", 0),
    ("Transformers_Get_strWdgCurrents", 0),
    ("Vsources_Get_Name", 0),
    ("XYCurves_Get_Name", 0),
    ("ReduceCkt_Get_EditString", 0),
    ("ReduceCkt_Get_StartPDElement", 0),
    ("ReduceCkt_Get_EnergyMeter", 0),
    ("Storages_Get_Name", 0),
    ("CNData_Get_Name", 0),
    ("LineGeometries_Get_Name", 0),
    ("LineSpacings_Get_Name", 0),
    ("Reactors_Get_Name", 0),
    ("Reactors_Get_Bus1", 0),
    ("Reactors_Get_Bus2", 0),
    ("Reactors_Get_RCurve", 0),
    ("Reactors_Get_LCurve", 0),
    ("TSData_Get_Name", 0),
    ("WireData_Get_Name", 0),
    ("WindGens_Get_Name", 0),
    ("WindGens_Get_daily", 0),
    ("WindGens_Get_duty", 0),
    ("WindGens_Get_Yearly", 0),
    ("WindGens_Get_Bus1", 0),
    ("ActiveClass_ToJSON", 1),
    ("Circuit_ToJSON", 1),
    ("CktElement_Get_Controller", 1),
    ("DSSElement_ToJSON", 1),
    ("DSS_Executive_Get_Command", 1),
    ("DSS_Executive_Get_Option", 1),
    ("DSS_Executive_Get_CommandHelp", 1),
    ("DSS_Executive_Get_OptionHelp", 1),
    ("DSS_Executive_Get_OptionValue", 1),
)

strlist_funcs = (
    ("ActiveClass_Get_AllNames", 0),
    ("Bus_Get_LineList", 0),
    ("Bus_Get_LoadList", 0),
    ("Bus_Get_AllPCEatBus", 0),
    ("Bus_Get_AllPDEatBus", 0),
    ("Capacitors_Get_AllNames", 0),
    ("CapControls_Get_AllNames", 0),
    ("Circuit_Get_AllElementNames", 0),
    ("Circuit_Get_AllBusNames", 0),
    ("Circuit_Get_AllNodeNames", 0),
    ("Circuit_Get_YNodeOrder", 0),
    ("CktElement_Get_BusNames", 0),
    ("CktElement_Get_AllPropertyNames", 0),
    ("CktElement_Get_AllVariableNames", 0),
    ("CtrlQueue_Get_Queue", 0),
    ("DSS_Get_Classes", 0),
    ("DSS_Get_UserClasses", 0),
    ("DSSElement_Get_AllPropertyNames", 0),
    ("Fuses_Get_AllNames", 0),
    ("Fuses_Get_State", 0),
    ("Fuses_Get_NormalState", 0),
    ("Generators_Get_AllNames", 0),
    ("Generators_Get_RegisterNames", 0),
    ("GICSources_Get_AllNames", 0),
    ("ISources_Get_AllNames", 0),
    ("LineCodes_Get_AllNames", 0),
    ("Lines_Get_AllNames", 0),
    ("Loads_Get_AllNames", 0),
    ("LoadShapes_Get_AllNames", 0),
    ("Meters_Get_AllNames", 0),
    ("Meters_Get_RegisterNames", 0),
    ("Meters_Get_AllEndElements", 0),
    ("Meters_Get_AllBranchesInZone", 0),
    ("Meters_Get_ZonePCE", 0),
    ("Monitors_Get_AllNames", 0),
    ("Monitors_Get_Header", 0),
    ("PDElements_Get_AllNames", 0),
    ("PVSystems_Get_AllNames", 0),
    ("PVSystems_Get_RegisterNames", 0),
    ("Reclosers_Get_AllNames", 0),
    ("RegControls_Get_AllNames", 0),
    ("Relays_Get_AllNames", 0),
    ("Sensors_Get_AllNames", 0),
    ("Solution_Get_EventLog", 0),
    ("Solution_Get_IncMatrixRows", 0),
    ("Solution_Get_IncMatrixCols", 0),
    ("SwtControls_Get_AllNames", 0),
    ("Topology_Get_AllIsolatedBranches", 0),
    ("Topology_Get_AllLoopedPairs", 0),
    ("Topology_Get_AllIsolatedLoads", 0),
    ("Transformers_Get_AllNames", 0),
    ("Vsources_Get_AllNames", 0),
    ("XYCurves_Get_AllNames", 0),
    ("Storages_Get_AllNames", 0),
    ("Storages_Get_RegisterNames", 0),
    ("CNData_Get_AllNames", 0),
    ("LineGeometries_Get_Conductors", 0),
    ("LineGeometries_Get_AllNames", 0),
    ("LineSpacings_Get_AllNames", 0),
    ("Reactors_Get_AllNames", 0),
    ("TSData_Get_AllNames", 0),
    ("WireData_Get_AllNames", 0),
    ("WindGens_Get_AllNames", 0),
    ("WindGens_Get_RegisterNames", 0),
    ("Circuit_Get_AllNodeNamesByPhase", 1),
    ("ZIP_List", 2),
)

f64arr_funcs = (
    ("Bus_Get_SeqVoltages_GR", 0, 3),
    ("Bus_Get_Voltages_GR", 0, 3),
    ("Bus_Get_Isc_GR", 0, 3),
    ("Bus_Get_Voc_GR", 0, 3),
    ("Bus_Get_puVoltages_GR", 0, 3),
    ("Bus_Get_Zsc0_GR", 0, 3),
    ("Bus_Get_Zsc1_GR", 0, 3),
    ("Bus_Get_ZscMatrix_GR", 0, 3),
    ("Bus_Get_YscMatrix_GR", 0, 3),
    ("Bus_Get_CplxSeqVoltages_GR", 0, 3),
    ("Bus_Get_puVLL_GR", 0, 3),
    ("Bus_Get_VLL_GR", 0, 3),
    ("Bus_Get_puVmagAngle_GR", 0, 3),
    ("Bus_Get_VMagAngle_GR", 0, 3),
    ("Bus_Get_ZSC012Matrix_GR", 0, 3),
    ("Circuit_Get_LineLosses_GR", 0, 3),
    ("Circuit_Get_Losses_GR", 0, 3),
    ("Circuit_Get_AllBusVmag_GR", 0, 3),
    ("Circuit_Get_AllBusVolts_GR", 0, 3),
    ("Circuit_Get_SubstationLosses_GR", 0, 3),
    ("Circuit_Get_TotalPower_GR", 0, 3),
    ("Circuit_Get_AllElementLosses_GR", 0, 3),
    ("Circuit_Get_AllBusVmagPu_GR", 0, 3),
    ("Circuit_Get_SystemY_GR", 0, 3),
    ("Circuit_Get_AllBusDistances_GR", 0, 3),
    ("Circuit_Get_AllNodeDistances_GR", 0, 3),
    ("Circuit_Get_YCurrents_GR", 0, 3),
    ("Circuit_Get_YNodeVarray_GR", 0, 3),
    ("CktElement_Get_Currents_GR", 0, 3),
    ("CktElement_Get_Voltages_GR", 0, 3),
    ("CktElement_Get_Losses_GR", 0, 3),
    ("CktElement_Get_PhaseLosses_GR", 0, 3),
    ("CktElement_Get_Powers_GR", 0, 3),
    ("CktElement_Get_SeqCurrents_GR", 0, 3),
    ("CktElement_Get_SeqPowers_GR", 0, 3),
    ("CktElement_Get_SeqVoltages_GR", 0, 3),
    ("CktElement_Get_Residuals_GR", 0, 3),
    ("CktElement_Get_Yprim_GR", 0, 3),
    ("CktElement_Get_CplxSeqVoltages_GR", 0, 3),
    ("CktElement_Get_CplxSeqCurrents_GR", 0, 3),
    ("CktElement_Get_AllVariableValues_GR", 0, 3),
    ("CktElement_Get_CurrentsMagAng_GR", 0, 3),
    ("CktElement_Get_VoltagesMagAng_GR", 0, 3),
    ("CktElement_Get_TotalPowers_GR", 0, 3),
    ("Generators_Get_RegisterValues_GR", 0, 3),
    ("LineCodes_Get_Cmatrix_GR", 0, 3),
    ("LineCodes_Get_Rmatrix_GR", 0, 3),
    ("LineCodes_Get_Xmatrix_GR", 0, 3),
    ("Lines_Get_Cmatrix_GR", 0, 3),
    ("Lines_Get_Rmatrix_GR", 0, 3),
    ("Lines_Get_Xmatrix_GR", 0, 3),
    ("Lines_Get_Yprim_GR", 0, 3),
    ("Loads_Get_ZIPV_GR", 0, 3),
    ("LoadShapes_Get_Pmult_GR", 0, 3),
    ("LoadShapes_Get_Qmult_GR", 0, 3),
    ("LoadShapes_Get_TimeArray_GR", 0, 3),
    ("Meters_Get_RegisterValues_GR", 0, 3),
    ("Meters_Get_Totals_GR", 0, 3),
    ("Meters_Get_Peakcurrent_GR", 0, 3),
    ("Meters_Get_CalcCurrent_GR", 0, 3),
    ("Meters_Get_AllocFactors_GR", 0, 3),
    ("Monitors_Get_dblFreq_GR", 0, 3),
    ("Monitors_Get_dblHour_GR", 0, 3),
    ("PDElements_Get_AllCurrents_GR", 0, 3),
    ("PDElements_Get_AllCurrentsMagAng_GR", 0, 3),
    ("PDElements_Get_AllCplxSeqCurrents_GR", 0, 3),
    ("PDElements_Get_AllSeqCurrents_GR", 0, 3),
    ("PDElements_Get_AllPowers_GR", 0, 3),
    ("PDElements_Get_AllSeqPowers_GR", 0, 3),
    ("PVSystems_Get_RegisterValues_GR", 0, 3),
    ("Reclosers_Get_RecloseIntervals_GR", 0, 3),
    ("Sensors_Get_Currents_GR", 0, 3),
    ("Sensors_Get_kVARS_GR", 0, 3),
    ("Sensors_Get_kVS_GR", 0, 3),
    ("Sensors_Get_kWS_GR", 0, 3),
    ("Sensors_Get_AllocationFactor_GR", 0, 3),
    ("Settings_Get_VoltageBases_GR", 0, 3),
    ("Transformers_Get_WdgVoltages_GR", 0, 3),
    ("Transformers_Get_WdgCurrents_GR", 0, 3),
    ("Transformers_Get_LossesByType_GR", 0, 3),
    ("Transformers_Get_AllLossesByType_GR", 0, 3),
    ("XYCurves_Get_Xarray_GR", 0, 3),
    ("XYCurves_Get_Yarray_GR", 0, 3),
    ("Storages_Get_RegisterValues_GR", 0, 3),
    ("LineGeometries_Get_Xcoords_GR", 0, 3),
    ("LineGeometries_Get_Ycoords_GR", 0, 3),
    ("LineSpacings_Get_Xcoords_GR", 0, 3),
    ("LineSpacings_Get_Ycoords_GR", 0, 3),
    ("Reactors_Get_Rmatrix_GR", 0, 3),
    ("Reactors_Get_Xmatrix_GR", 0, 3),
    ("Reactors_Get_Z_GR", 0, 3),
    ("Reactors_Get_Z1_GR", 0, 3),
    ("Reactors_Get_Z2_GR", 0, 3),
    ("Reactors_Get_Z0_GR", 0, 3),
    ("WindGens_Get_RegisterValues_GR", 0, 3),
    ("Circuit_Get_AllNodeDistancesByPhase_GR", 1, 3),
    ("Circuit_Get_AllNodeVmagByPhase_GR", 1, 3),
    ("Circuit_Get_AllNodeVmagPUByPhase_GR", 1, 3),
    ("Monitors_Get_Channel_GR", 1, 3),
    ("Parser_Get_Vector_GR", 1, 3),
    ("Parser_Get_Matrix_GR", 1, 3),
    ("Parser_Get_SymMatrix_GR", 1, 3),
)

i32arr_funcs = (
    ("Bus_Get_Nodes_GR", 0, 1),
    ("Capacitors_Get_States_GR", 0, 1),
    ("CktElement_Get_NodeOrder_GR", 0, 1),
    ("Parallel_Get_ActorProgress_GR", 0, 1),
    ("Parallel_Get_ActorStatus_GR", 0, 1),
    ("PDElements_Get_AllNumPhases_GR", 0, 1),
    ("PDElements_Get_AllNumConductors_GR", 0, 1),
    ("PDElements_Get_AllNumTerminals_GR", 0, 1),
    ("Settings_Get_LossRegs_GR", 0, 1),
    ("Settings_Get_UEregs_GR", 0, 1),
    ("Solution_Get_IncMatrix_GR", 0, 1),
    ("Solution_Get_Laplacian_GR", 0, 1),
    ("Solution_Get_BusLevels_GR", 0, 1),
    ("LineGeometries_Get_Units_GR", 0, 1),
    ("CktElement_Get_NodeRef_GR", 0, 1),
)

i8arr_funcs = (
    ("Monitors_Get_ByteStream_GR", 0, 5),
)

