from enum import IntEnum

class Signatures(IntEnum):
    Empty = 0
    Int32 = 1
    String = 2
    Float64 = 3
    Complex128 = 4
    Int8 = 5
    Float32 = 6
    Complex64 = 7
    OneComplex128 = 8
    OneInt32 = 9
    OneFloat64 = 10

str_funcs = (
    ("ActiveClass_Get_Name", 0),
    ("ActiveClass_Get_ActiveClassName", 0),
    ("ActiveClass_Get_ActiveClassParent", 0),
    ("Bus_Get_Name", 0),
    ("Capacitors_Get_Name", 0),
    ("CapControls_Get_Capacitor", 0),
    ("CapControls_Get_MonitoredObj", 0),
    ("CapControls_Get_Name", 0),
    ("Circuit_Get_Name", 0),
    ("CktElement_Get_Name", 0),
    ("CktElement_Get_DisplayName", 0),
    ("CktElement_Get_GUID", 0),
    ("CktElement_Get_EnergyMeter", 0),
    ("CktElement_Get_VariableName", 0),
    ("DSS_Get_Version", 0),
    ("DSS_Get_DataPath", 0),
    ("DSS_Get_DefaultEditor", 0),
    ("DSSElement_Get_Name", 0),
    ("DSSProperty_Get_Description", 0),
    ("DSSProperty_Get_Name", 0),
    ("DSSProperty_Get_Val", 0),
    ("Error_Get_Description", 0),
    ("Fuses_Get_Name", 0),
    ("Fuses_Get_MonitoredObj", 0),
    ("Fuses_Get_SwitchedObj", 0),
    ("Fuses_Get_TCCcurve", 0),
    ("Generators_Get_Name", 0),
    ("Generators_Get_daily", 0),
    ("Generators_Get_duty", 0),
    ("Generators_Get_Yearly", 0),
    ("Generators_Get_Bus1", 0),
    ("GICSources_Get_Name", 0),
    ("GICSources_Get_Bus1", 0),
    ("GICSources_Get_Bus2", 0),
    ("ISources_Get_Name", 0),
    ("LineCodes_Get_Name", 0),
    ("Lines_Get_Bus1", 0),
    ("Lines_Get_Bus2", 0),
    ("Lines_Get_LineCode", 0),
    ("Lines_Get_Name", 0),
    ("Lines_Get_Geometry", 0),
    ("Lines_Get_Spacing", 0),
    ("Loads_Get_Name", 0),
    ("Loads_Get_CVRcurve", 0),
    ("Loads_Get_daily", 0),
    ("Loads_Get_duty", 0),
    ("Loads_Get_Growth", 0),
    ("Loads_Get_Spectrum", 0),
    ("Loads_Get_Yearly", 0),
    ("Loads_Get_Sensor", 0),
    ("LoadShapes_Get_Name", 0),
    ("Meters_Get_Name", 0),
    ("Meters_Get_MeteredElement", 0),
    ("Monitors_Get_FileName", 0),
    ("Monitors_Get_Name", 0),
    ("Monitors_Get_Element", 0),
    ("Parser_Get_CmdString", 0),
    ("Parser_Get_NextParam", 0),
    ("Parser_Get_StrValue", 0),
    ("Parser_Get_WhiteSpace", 0),
    ("Parser_Get_BeginQuote", 0),
    ("Parser_Get_EndQuote", 0),
    ("Parser_Get_Delimiters", 0),
    ("PDElements_Get_Name", 0),
    ("PVSystems_Get_Name", 0),
    ("PVSystems_Get_daily", 0),
    ("PVSystems_Get_duty", 0),
    ("PVSystems_Get_yearly", 0),
    ("PVSystems_Get_Tdaily", 0),
    ("PVSystems_Get_Tduty", 0),
    ("PVSystems_Get_Tyearly", 0),
    ("PVSystems_Get_Sensor", 0),
    ("Reclosers_Get_Name", 0),
    ("Reclosers_Get_SwitchedObj", 0),
    ("Reclosers_Get_MonitoredObj", 0),
    ("RegControls_Get_MonitoredBus", 0),
    ("RegControls_Get_Name", 0),
    ("RegControls_Get_Transformer", 0),
    ("Relays_Get_Name", 0),
    ("Relays_Get_MonitoredObj", 0),
    ("Relays_Get_SwitchedObj", 0),
    ("Sensors_Get_MeteredElement", 0),
    ("Sensors_Get_Name", 0),
    ("Settings_Get_AutoBusList", 0),
    ("Settings_Get_PriceCurve", 0),
    ("Solution_Get_ModeID", 0),
    ("Solution_Get_LDCurve", 0),
    ("Solution_Get_DefaultDaily", 0),
    ("Solution_Get_DefaultYearly", 0),
    ("SwtControls_Get_Name", 0),
    ("SwtControls_Get_SwitchedObj", 0),
    ("Text_Get_Command", 0),
    ("Text_Get_Result", 0),
    ("Topology_Get_BranchName", 0),
    ("Topology_Get_BusName", 0),
    ("Transformers_Get_Name", 0),
    ("Transformers_Get_XfmrCode", 0),
    ("Transformers_Get_strWdgCurrents", 0),
    ("Vsources_Get_Name", 0),
    ("XYCurves_Get_Name", 0),
    ("ReduceCkt_Get_EditString", 0),
    ("ReduceCkt_Get_StartPDElement", 0),
    ("ReduceCkt_Get_EnergyMeter", 0),
    ("Storages_Get_Name", 0),
    ("CNData_Get_Name", 0),
    ("LineGeometries_Get_Name", 0),
    ("LineSpacings_Get_Name", 0),
    ("Reactors_Get_Name", 0),
    ("Reactors_Get_Bus1", 0),
    ("Reactors_Get_Bus2", 0),
    ("Reactors_Get_RCurve", 0),
    ("Reactors_Get_LCurve", 0),
    ("TSData_Get_Name", 0),
    ("WireData_Get_Name", 0),
    ("WindGens_Get_Name", 0),
    ("WindGens_Get_daily", 0),
    ("WindGens_Get_duty", 0),
    ("WindGens_Get_Yearly", 0),
    ("WindGens_Get_Bus1", 0),
    ("ActiveClass_ToJSON", 1),
    ("Circuit_ToJSON", 1),
    ("CktElement_Get_Controller", 1),
    ("DSSElement_ToJSON", 1),
    ("DSS_Executive_Get_Command", 1),
    ("DSS_Executive_Get_Option", 1),
    ("DSS_Executive_Get_CommandHelp", 1),
    ("DSS_Executive_Get_OptionHelp", 1),
    ("DSS_Executive_Get_OptionValue", 1),
)

strlist_funcs = (
    ("ActiveClass_Get_AllNames", 0),
    ("Bus_Get_LineList", 0),
    ("Bus_Get_LoadList", 0),
    ("Bus_Get_AllPCEatBus", 0),
    ("Bus_Get_AllPDEatBus", 0),
    ("Capacitors_Get_AllNames", 0),
    ("CapControls_Get_AllNames", 0),
    ("Circuit_Get_AllElementNames", 0),
    ("Circuit_Get_AllBusNames", 0),
    ("Circuit_Get_AllNodeNames", 0),
    ("Circuit_Get_YNodeOrder", 0),
    ("CktElement_Get_BusNames", 0),
    ("CktElement_Get_AllPropertyNames", 0),
    ("CktElement_Get_AllVariableNames", 0),
    ("CtrlQueue_Get_Queue", 0),
    ("DSS_Get_Classes", 0),
    ("DSS_Get_UserClasses", 0),
    ("DSSElement_Get_AllPropertyNames", 0),
    ("Fuses_Get_AllNames", 0),
    ("Fuses_Get_State", 0),
    ("Fuses_Get_NormalState", 0),
    ("Generators_Get_AllNames", 0),
    ("Generators_Get_RegisterNames", 0),
    ("GICSources_Get_AllNames", 0),
    ("ISources_Get_AllNames", 0),
    ("LineCodes_Get_AllNames", 0),
    ("Lines_Get_AllNames", 0),
    ("Loads_Get_AllNames", 0),
    ("LoadShapes_Get_AllNames", 0),
    ("Meters_Get_AllNames", 0),
    ("Meters_Get_RegisterNames", 0),
    ("Meters_Get_AllEndElements", 0),
    ("Meters_Get_AllBranchesInZone", 0),
    ("Meters_Get_ZonePCE", 0),
    ("Monitors_Get_AllNames", 0),
    ("Monitors_Get_Header", 0),
    ("PDElements_Get_AllNames", 0),
    ("PVSystems_Get_AllNames", 0),
    ("PVSystems_Get_RegisterNames", 0),
    ("Reclosers_Get_AllNames", 0),
    ("RegControls_Get_AllNames", 0),
    ("Relays_Get_AllNames", 0),
    ("Sensors_Get_AllNames", 0),
    ("Solution_Get_EventLog", 0),
    ("Solution_Get_IncMatrixRows", 0),
    ("Solution_Get_IncMatrixCols", 0),
    ("SwtControls_Get_AllNames", 0),
    ("Topology_Get_AllIsolatedBranches", 0),
    ("Topology_Get_AllLoopedPairs", 0),
    ("Topology_Get_AllIsolatedLoads", 0),
    ("Transformers_Get_AllNames", 0),
    ("Vsources_Get_AllNames", 0),
    ("XYCurves_Get_AllNames", 0),
    ("Storages_Get_AllNames", 0),
    ("Storages_Get_RegisterNames", 0),
    ("CNData_Get_AllNames", 0),
    ("LineGeometries_Get_Conductors", 0),
    ("LineGeometries_Get_AllNames", 0),
    ("LineSpacings_Get_AllNames", 0),
    ("Reactors_Get_AllNames", 0),
    ("TSData_Get_AllNames", 0),
    ("WireData_Get_AllNames", 0),
    ("WindGens_Get_AllNames", 0),
    ("WindGens_Get_RegisterNames", 0),
    ("Circuit_Get_AllNodeNamesByPhase", 1),
    ("ZIP_List", 2),
)

f64arr_funcs = (
    ("Bus_Get_SeqVoltages_GR", 0, 3),
    ("Bus_Get_Voltages_GR", 0, 3),
    ("Bus_Get_Isc_GR", 0, 3),
    ("Bus_Get_Voc_GR", 0, 3),
    ("Bus_Get_puVoltages_GR", 0, 3),
    ("Bus_Get_Zsc0_GR", 0, 3),
    ("Bus_Get_Zsc1_GR", 0, 3),
    ("Bus_Get_ZscMatrix_GR", 0, 3),
    ("Bus_Get_YscMatrix_GR", 0, 3),
    ("Bus_Get_CplxSeqVoltages_GR", 0, 3),
    ("Bus_Get_puVLL_GR", 0, 3),
    ("Bus_Get_VLL_GR", 0, 3),
    ("Bus_Get_puVmagAngle_GR", 0, 3),
    ("Bus_Get_VMagAngle_GR", 0, 3),
    ("Bus_Get_ZSC012Matrix_GR", 0, 3),
    ("Circuit_Get_LineLosses_GR", 0, 3),
    ("Circuit_Get_Losses_GR", 0, 3),
    ("Circuit_Get_AllBusVmag_GR", 0, 3),
    ("Circuit_Get_AllBusVolts_GR", 0, 3),
    ("Circuit_Get_SubstationLosses_GR", 0, 3),
    ("Circuit_Get_TotalPower_GR", 0, 3),
    ("Circuit_Get_AllElementLosses_GR", 0, 3),
    ("Circuit_Get_AllBusVmagPu_GR", 0, 3),
    ("Circuit_Get_SystemY_GR", 0, 3),
    ("Circuit_Get_AllBusDistances_GR", 0, 3),
    ("Circuit_Get_AllNodeDistances_GR", 0, 3),
    ("Circuit_Get_YCurrents_GR", 0, 3),
    ("Circuit_Get_YNodeVarray_GR", 0, 3),
    ("CktElement_Get_Currents_GR", 0, 3),
    ("CktElement_Get_Voltages_GR", 0, 3),
    ("CktElement_Get_Losses_GR", 0, 3),
    ("CktElement_Get_PhaseLosses_GR", 0, 3),
    ("CktElement_Get_Powers_GR", 0, 3),
    ("CktElement_Get_SeqCurrents_GR", 0, 3),
    ("CktElement_Get_SeqPowers_GR", 0, 3),
    ("CktElement_Get_SeqVoltages_GR", 0, 3),
    ("CktElement_Get_Residuals_GR", 0, 3),
    ("CktElement_Get_Yprim_GR", 0, 3),
    ("CktElement_Get_CplxSeqVoltages_GR", 0, 3),
    ("CktElement_Get_CplxSeqCurrents_GR", 0, 3),
    ("CktElement_Get_AllVariableValues_GR", 0, 3),
    ("CktElement_Get_CurrentsMagAng_GR", 0, 3),
    ("CktElement_Get_VoltagesMagAng_GR", 0, 3),
    ("CktElement_Get_TotalPowers_GR", 0, 3),
    ("Generators_Get_RegisterValues_GR", 0, 3),
    ("LineCodes_Get_Cmatrix_GR", 0, 3),
    ("LineCodes_Get_Rmatrix_GR", 0, 3),
    ("LineCodes_Get_Xmatrix_GR", 0, 3),
    ("Lines_Get_Cmatrix_GR", 0, 3),
    ("Lines_Get_Rmatrix_GR", 0, 3),
    ("Lines_Get_Xmatrix_GR", 0, 3),
    ("Lines_Get_Yprim_GR", 0, 3),
    ("Loads_Get_ZIPV_GR", 0, 3),
    ("LoadShapes_Get_Pmult_GR", 0, 3),
    ("LoadShapes_Get_Qmult_GR", 0, 3),
    ("LoadShapes_Get_TimeArray_GR", 0, 3),
    ("Meters_Get_RegisterValues_GR", 0, 3),
    ("Meters_Get_Totals_GR", 0, 3),
    ("Meters_Get_Peakcurrent_GR", 0, 3),
    ("Meters_Get_CalcCurrent_GR", 0, 3),
    ("Meters_Get_AllocFactors_GR", 0, 3),
    ("Monitors_Get_dblFreq_GR", 0, 3),
    ("Monitors_Get_dblHour_GR", 0, 3),
    ("PDElements_Get_AllCurrents_GR", 0, 3),
    ("PDElements_Get_AllCurrentsMagAng_GR", 0, 3),
    ("PDElements_Get_AllCplxSeqCurrents_GR", 0, 3),
    ("PDElements_Get_AllSeqCurrents_GR", 0, 3),
    ("PDElements_Get_AllPowers_GR", 0, 3),
    ("PDElements_Get_AllSeqPowers_GR", 0, 3),
    ("PVSystems_Get_RegisterValues_GR", 0, 3),
    ("Reclosers_Get_RecloseIntervals_GR", 0, 3),
    ("Sensors_Get_Currents_GR", 0, 3),
    ("Sensors_Get_kVARS_GR", 0, 3),
    ("Sensors_Get_kVS_GR", 0, 3),
    ("Sensors_Get_kWS_GR", 0, 3),
    ("Sensors_Get_AllocationFactor_GR", 0, 3),
    ("Settings_Get_VoltageBases_GR", 0, 3),
    ("Transformers_Get_WdgVoltages_GR", 0, 3),
    ("Transformers_Get_WdgCurrents_GR", 0, 3),
    ("Transformers_Get_LossesByType_GR", 0, 3),
    ("Transformers_Get_AllLossesByType_GR", 0, 3),
    ("XYCurves_Get_Xarray_GR", 0, 3),
    ("XYCurves_Get_Yarray_GR", 0, 3),
    ("Storages_Get_RegisterValues_GR", 0, 3),
    ("LineGeometries_Get_Xcoords_GR", 0, 3),
    ("LineGeometries_Get_Ycoords_GR", 0, 3),
    ("LineSpacings_Get_Xcoords_GR", 0, 3),
    ("LineSpacings_Get_Ycoords_GR", 0, 3),
    ("Reactors_Get_Rmatrix_GR", 0, 3),
    ("Reactors_Get_Xmatrix_GR", 0, 3),
    ("Reactors_Get_Z_GR", 0, 3),
    ("Reactors_Get_Z1_GR", 0, 3),
    ("Reactors_Get_Z2_GR", 0, 3),
    ("Reactors_Get_Z0_GR", 0, 3),
    ("WindGens_Get_RegisterValues_GR", 0, 3),
    ("Circuit_Get_AllNodeDistancesByPhase_GR", 1, 3),
    ("Circuit_Get_AllNodeVmagByPhase_GR", 1, 3),
    ("Circuit_Get_AllNodeVmagPUByPhase_GR", 1, 3),
    ("Monitors_Get_Channel_GR", 1, 3),
    ("Parser_Get_Vector_GR", 1, 3),
    ("Parser_Get_Matrix_GR", 1, 3),
    ("Parser_Get_SymMatrix_GR", 1, 3),
)

i32arr_funcs = (
    ("Bus_Get_Nodes_GR", 0, 1),
    ("Capacitors_Get_States_GR", 0, 1),
    ("CktElement_Get_NodeOrder_GR", 0, 1),
    ("Parallel_Get_ActorProgress_GR", 0, 1),
    ("Parallel_Get_ActorStatus_GR", 0, 1),
    ("PDElements_Get_AllNumPhases_GR", 0, 1),
    ("PDElements_Get_AllNumConductors_GR", 0, 1),
    ("PDElements_Get_AllNumTerminals_GR", 0, 1),
    ("Settings_Get_LossRegs_GR", 0, 1),
    ("Settings_Get_UEregs_GR", 0, 1),
    ("Solution_Get_IncMatrix_GR", 0, 1),
    ("Solution_Get_Laplacian_GR", 0, 1),
    ("Solution_Get_BusLevels_GR", 0, 1),
    ("LineGeometries_Get_Units_GR", 0, 1),
    ("CktElement_Get_NodeRef_GR", 0, 1),
)

i8arr_funcs = (
    ("Monitors_Get_ByteStream_GR", 0, 5),
)

i32_funcs = (
    ("ActiveClass_Get_First", 0, 9),
    ("ActiveClass_Get_Next", 0, 9),
    ("ActiveClass_Get_NumElements", 0, 9),
    ("ActiveClass_Get_Count", 0, 9),
    ("Bus_Get_NumNodes", 0, 9),
    ("Bus_Get_N_Customers", 0, 9),
    ("Bus_Get_SectionID", 0, 9),
    ("Capacitors_Get_First", 0, 9),
    ("Capacitors_Get_Next", 0, 9),
    ("Capacitors_Get_NumSteps", 0, 9),
    ("Capacitors_Get_Count", 0, 9),
    ("Capacitors_Get_AvailableSteps", 0, 9),
    ("CapControls_Get_First", 0, 9),
    ("CapControls_Get_Mode", 0, 9),
    ("CapControls_Get_MonitoredTerm", 0, 9),
    ("CapControls_Get_Next", 0, 9),
    ("CapControls_Get_Count", 0, 9),
    ("Circuit_Get_NumBuses", 0, 9),
    ("Circuit_Get_NumCktElements", 0, 9),
    ("Circuit_Get_NumNodes", 0, 9),
    ("Circuit_FirstPCElement", 0, 9),
    ("Circuit_FirstPDElement", 0, 9),
    ("Circuit_NextPCElement", 0, 9),
    ("Circuit_NextPDElement", 0, 9),
    ("Circuit_FirstElement", 0, 9),
    ("Circuit_NextElement", 0, 9),
    ("Circuit_Get_ParentPDElement", 0, 9),
    ("CktElement_Get_NumConductors", 0, 9),
    ("CktElement_Get_NumPhases", 0, 9),
    ("CktElement_Get_NumTerminals", 0, 9),
    ("CktElement_Get_NumProperties", 0, 9),
    ("CktElement_Get_Handle", 0, 9),
    ("CktElement_Get_NumControls", 0, 9),
    ("CktElement_Get_OCPDevIndex", 0, 9),
    ("CktElement_Get_OCPDevType", 0, 9),
    ("CktElement_Get_VariableIdx", 0, 9),
    ("CtrlQueue_Get_ActionCode", 0, 9),
    ("CtrlQueue_Get_DeviceHandle", 0, 9),
    ("CtrlQueue_Get_NumActions", 0, 9),
    ("CtrlQueue_Get_PopAction", 0, 9),
    ("CtrlQueue_Get_QueueSize", 0, 9),
    ("DSS_Get_NumCircuits", 0, 9),
    ("DSS_Get_NumClasses", 0, 9),
    ("DSS_Get_NumUserClasses", 0, 9),
    ("DSSElement_Get_NumProperties", 0, 9),
    ("DSS_Executive_Get_NumCommands", 0, 9),
    ("DSS_Executive_Get_NumOptions", 0, 9),
    ("Error_Get_Number", 0, 9),
    ("Fuses_Get_Count", 0, 9),
    ("Fuses_Get_First", 0, 9),
    ("Fuses_Get_Next", 0, 9),
    ("Fuses_Get_MonitoredTerm", 0, 9),
    ("Fuses_Get_SwitchedTerm", 0, 9),
    ("Fuses_Get_idx", 0, 9),
    ("Fuses_Get_NumPhases", 0, 9),
    ("Generators_Get_First", 0, 9),
    ("Generators_Get_Next", 0, 9),
    ("Generators_Get_Phases", 0, 9),
    ("Generators_Get_Count", 0, 9),
    ("Generators_Get_idx", 0, 9),
    ("Generators_Get_Model", 0, 9),
    ("Generators_Get_Status", 0, 9),
    ("Generators_Get_Class_", 0, 9),
    ("GICSources_Get_Count", 0, 9),
    ("GICSources_Get_First", 0, 9),
    ("GICSources_Get_Next", 0, 9),
    ("GICSources_Get_Phases", 0, 9),
    ("ISources_Get_Count", 0, 9),
    ("ISources_Get_First", 0, 9),
    ("ISources_Get_Next", 0, 9),
    ("LineCodes_Get_Count", 0, 9),
    ("LineCodes_Get_First", 0, 9),
    ("LineCodes_Get_Next", 0, 9),
    ("LineCodes_Get_Units", 0, 9),
    ("LineCodes_Get_Phases", 0, 9),
    ("Lines_Get_First", 0, 9),
    ("Lines_Get_Next", 0, 9),
    ("Lines_Get_Phases", 0, 9),
    ("Lines_Get_NumCust", 0, 9),
    ("Lines_Get_TotalCust", 0, 9),
    ("Lines_Get_Parent", 0, 9),
    ("Lines_Get_Count", 0, 9),
    ("Lines_Get_Units", 0, 9),
    ("Loads_Get_First", 0, 9),
    ("Loads_Get_idx", 0, 9),
    ("Loads_Get_Next", 0, 9),
    ("Loads_Get_Count", 0, 9),
    ("Loads_Get_Class_", 0, 9),
    ("Loads_Get_Model", 0, 9),
    ("Loads_Get_NumCust", 0, 9),
    ("Loads_Get_Status", 0, 9),
    ("LoadShapes_Get_Count", 0, 9),
    ("LoadShapes_Get_First", 0, 9),
    ("LoadShapes_Get_Next", 0, 9),
    ("LoadShapes_Get_Npts", 0, 9),
    ("Meters_Get_First", 0, 9),
    ("Meters_Get_Next", 0, 9),
    ("Meters_Get_MeteredTerminal", 0, 9),
    ("Meters_Get_CountEndElements", 0, 9),
    ("Meters_Get_Count", 0, 9),
    ("Meters_Get_CountBranches", 0, 9),
    ("Meters_Get_SequenceIndex", 0, 9),
    ("Meters_Get_SeqListSize", 0, 9),
    ("Meters_Get_TotalCustomers", 0, 9),
    ("Meters_Get_NumSections", 0, 9),
    ("Meters_Get_NumSectionBranches", 0, 9),
    ("Meters_Get_NumSectionCustomers", 0, 9),
    ("Meters_Get_OCPDeviceType", 0, 9),
    ("Meters_Get_SectSeqIdx", 0, 9),
    ("Meters_Get_SectTotalCust", 0, 9),
    ("Monitors_Get_First", 0, 9),
    ("Monitors_Get_Mode", 0, 9),
    ("Monitors_Get_Next", 0, 9),
    ("Monitors_Get_SampleCount", 0, 9),
    ("Monitors_Get_Count", 0, 9),
    ("Monitors_Get_FileVersion", 0, 9),
    ("Monitors_Get_NumChannels", 0, 9),
    ("Monitors_Get_RecordSize", 0, 9),
    ("Monitors_Get_Terminal", 0, 9),
    ("Parallel_Get_NumCPUs", 0, 9),
    ("Parallel_Get_NumCores", 0, 9),
    ("Parallel_Get_ActiveActor", 0, 9),
    ("Parallel_Get_ActorCPU", 0, 9),
    ("Parallel_Get_NumOfActors", 0, 9),
    ("Parallel_Get_ActiveParallel", 0, 9),
    ("Parallel_Get_ConcatenateReports", 0, 9),
    ("Parser_Get_IntValue", 0, 9),
    ("PDElements_Get_Count", 0, 9),
    ("PDElements_Get_First", 0, 9),
    ("PDElements_Get_Next", 0, 9),
    ("PDElements_Get_Numcustomers", 0, 9),
    ("PDElements_Get_ParentPDElement", 0, 9),
    ("PDElements_Get_Totalcustomers", 0, 9),
    ("PDElements_Get_FromTerminal", 0, 9),
    ("PDElements_Get_SectionID", 0, 9),
    ("PVSystems_Get_First", 0, 9),
    ("PVSystems_Get_Next", 0, 9),
    ("PVSystems_Get_Count", 0, 9),
    ("PVSystems_Get_idx", 0, 9),
    ("Reclosers_Get_Count", 0, 9),
    ("Reclosers_Get_First", 0, 9),
    ("Reclosers_Get_Next", 0, 9),
    ("Reclosers_Get_MonitoredTerm", 0, 9),
    ("Reclosers_Get_SwitchedTerm", 0, 9),
    ("Reclosers_Get_NumFast", 0, 9),
    ("Reclosers_Get_Shots", 0, 9),
    ("Reclosers_Get_idx", 0, 9),
    ("Reclosers_Get_State", 0, 9),
    ("Reclosers_Get_NormalState", 0, 9),
    ("RegControls_Get_First", 0, 9),
    ("RegControls_Get_MaxTapChange", 0, 9),
    ("RegControls_Get_Next", 0, 9),
    ("RegControls_Get_TapWinding", 0, 9),
    ("RegControls_Get_Winding", 0, 9),
    ("RegControls_Get_TapNumber", 0, 9),
    ("RegControls_Get_Count", 0, 9),
    ("Relays_Get_Count", 0, 9),
    ("Relays_Get_First", 0, 9),
    ("Relays_Get_Next", 0, 9),
    ("Relays_Get_MonitoredTerm", 0, 9),
    ("Relays_Get_SwitchedTerm", 0, 9),
    ("Relays_Get_idx", 0, 9),
    ("Relays_Get_State", 0, 9),
    ("Relays_Get_NormalState", 0, 9),
    ("Sensors_Get_Count", 0, 9),
    ("Sensors_Get_First", 0, 9),
    ("Sensors_Get_MeteredTerminal", 0, 9),
    ("Sensors_Get_Next", 0, 9),
    ("Settings_Get_CktModel", 0, 9),
    ("Settings_Get_IterateDisabled", 0, 9),
    ("Solution_Get_Hour", 0, 9),
    ("Solution_Get_Iterations", 0, 9),
    ("Solution_Get_MaxIterations", 0, 9),
    ("Solution_Get_Mode", 0, 9),
    ("Solution_Get_Number", 0, 9),
    ("Solution_Get_Random", 0, 9),
    ("Solution_Get_Year", 0, 9),
    ("Solution_Get_LoadModel", 0, 9),
    ("Solution_Get_AddType", 0, 9),
    ("Solution_Get_Algorithm", 0, 9),
    ("Solution_Get_ControlMode", 0, 9),
    ("Solution_Get_ControlIterations", 0, 9),
    ("Solution_Get_MaxControlIterations", 0, 9),
    ("Solution_Get_Totaliterations", 0, 9),
    ("Solution_Get_MostIterationsDone", 0, 9),
    ("Solution_Get_MinIterations", 0, 9),
    ("SwtControls_Get_Action", 0, 9),
    ("SwtControls_Get_First", 0, 9),
    ("SwtControls_Get_Next", 0, 9),
    ("SwtControls_Get_SwitchedTerm", 0, 9),
    ("SwtControls_Get_Count", 0, 9),
    ("SwtControls_Get_NormalState", 0, 9),
    ("SwtControls_Get_State", 0, 9),
    ("Topology_Get_NumLoops", 0, 9),
    ("Topology_Get_ActiveBranch", 0, 9),
    ("Topology_Get_BackwardBranch", 0, 9),
    ("Topology_Get_First", 0, 9),
    ("Topology_Get_ForwardBranch", 0, 9),
    ("Topology_Get_LoopedBranch", 0, 9),
    ("Topology_Get_Next", 0, 9),
    ("Topology_Get_NumIsolatedBranches", 0, 9),
    ("Topology_Get_ParallelBranch", 0, 9),
    ("Topology_Get_FirstLoad", 0, 9),
    ("Topology_Get_NextLoad", 0, 9),
    ("Topology_Get_NumIsolatedLoads", 0, 9),
    ("Topology_Get_ActiveLevel", 0, 9),
    ("Transformers_Get_First", 0, 9),
    ("Transformers_Get_Next", 0, 9),
    ("Transformers_Get_NumTaps", 0, 9),
    ("Transformers_Get_NumWindings", 0, 9),
    ("Transformers_Get_Wdg", 0, 9),
    ("Transformers_Get_Count", 0, 9),
    ("Transformers_Get_CoreType", 0, 9),
    ("Vsources_Get_Count", 0, 9),
    ("Vsources_Get_First", 0, 9),
    ("Vsources_Get_Next", 0, 9),
    ("Vsources_Get_Phases", 0, 9),
    ("XYCurves_Get_Count", 0, 9),
    ("XYCurves_Get_First", 0, 9),
    ("XYCurves_Get_Next", 0, 9),
    ("XYCurves_Get_Npts", 0, 9),
    ("Storages_Get_First", 0, 9),
    ("Storages_Get_Next", 0, 9),
    ("Storages_Get_Count", 0, 9),
    ("Storages_Get_idx", 0, 9),
    ("Storages_Get_State", 0, 9),
    ("Storages_Get_ControlMode", 0, 9),
    ("Storages_Get_SafeMode", 0, 9),
    ("Storages_Get_VarFollowInverter", 0, 9),
    ("CNData_Get_Count", 0, 9),
    ("CNData_Get_First", 0, 9),
    ("CNData_Get_Next", 0, 9),
    ("CNData_Get_GMRUnits", 0, 9),
    ("CNData_Get_RadiusUnits", 0, 9),
    ("CNData_Get_ResistanceUnits", 0, 9),
    ("CNData_Get_k", 0, 9),
    ("LineGeometries_Get_Count", 0, 9),
    ("LineGeometries_Get_First", 0, 9),
    ("LineGeometries_Get_Next", 0, 9),
    ("LineGeometries_Get_Nconds", 0, 9),
    ("LineGeometries_Get_Phases", 0, 9),
    ("LineSpacings_Get_Count", 0, 9),
    ("LineSpacings_Get_First", 0, 9),
    ("LineSpacings_Get_Next", 0, 9),
    ("LineSpacings_Get_Nconds", 0, 9),
    ("LineSpacings_Get_Phases", 0, 9),
    ("LineSpacings_Get_Units", 0, 9),
    ("Loads_Get_Phases", 0, 9),
    ("Reactors_Get_First", 0, 9),
    ("Reactors_Get_Next", 0, 9),
    ("Reactors_Get_Count", 0, 9),
    ("Reactors_Get_Phases", 0, 9),
    ("Reactors_Get_SpecType", 0, 9),
    ("TSData_Get_Count", 0, 9),
    ("TSData_Get_First", 0, 9),
    ("TSData_Get_Next", 0, 9),
    ("TSData_Get_GMRUnits", 0, 9),
    ("TSData_Get_RadiusUnits", 0, 9),
    ("TSData_Get_ResistanceUnits", 0, 9),
    ("WireData_Get_Count", 0, 9),
    ("WireData_Get_First", 0, 9),
    ("WireData_Get_Next", 0, 9),
    ("WireData_Get_GMRUnits", 0, 9),
    ("WireData_Get_RadiusUnits", 0, 9),
    ("WireData_Get_ResistanceUnits", 0, 9),
    ("Bus_Get_Next", 0, 9),
    ("CNData_Get_idx", 0, 9),
    ("CapControls_Get_idx", 0, 9),
    ("Capacitors_Get_idx", 0, 9),
    ("GICSources_Get_idx", 0, 9),
    ("ISources_Get_idx", 0, 9),
    ("LineCodes_Get_idx", 0, 9),
    ("LineGeometries_Get_idx", 0, 9),
    ("LineSpacings_Get_idx", 0, 9),
    ("Lines_Get_idx", 0, 9),
    ("LoadShapes_Get_idx", 0, 9),
    ("Meters_Get_idx", 0, 9),
    ("Monitors_Get_idx", 0, 9),
    ("Reactors_Get_idx", 0, 9),
    ("RegControls_Get_idx", 0, 9),
    ("Sensors_Get_idx", 0, 9),
    ("SwtControls_Get_idx", 0, 9),
    ("TSData_Get_idx", 0, 9),
    ("Transformers_Get_idx", 0, 9),
    ("Vsources_Get_idx", 0, 9),
    ("WireData_Get_idx", 0, 9),
    ("XYCurves_Get_idx", 0, 9),
    ("WindGens_Get_First", 0, 9),
    ("WindGens_Get_Next", 0, 9),
    ("WindGens_Get_Count", 0, 9),
    ("WindGens_Get_idx", 0, 9),
    ("WindGens_Get_N_WTG", 0, 9),
    ("WindGens_Get_NPoles", 0, 9),
    ("WindGens_Get_QFlag", 0, 9),
    ("WindGens_Get_QMode", 0, 9),
    ("WindGens_Get_Phases", 0, 9),
    ("WindGens_Get_Class_", 0, 9),
    ("YMatrix_Get_Iteration", 0, 9),
    ("Bus_GetUniqueNodeNumber", 9, 9),
    ("Circuit_SetActiveBusi", 9, 9),
)

f64_funcs = (
    ("Bus_Get_kVBase", 0, 10),
    ("Bus_Get_x", 0, 10),
    ("Bus_Get_y", 0, 10),
    ("Bus_Get_Distance", 0, 10),
    ("Bus_Get_Int_Duration", 0, 10),
    ("Bus_Get_Lambda", 0, 10),
    ("Bus_Get_Cust_Duration", 0, 10),
    ("Bus_Get_Cust_Interrupts", 0, 10),
    ("Bus_Get_N_interrupts", 0, 10),
    ("Bus_Get_TotalMiles", 0, 10),
    ("Capacitors_Get_kV", 0, 10),
    ("Capacitors_Get_kvar", 0, 10),
    ("CapControls_Get_CTratio", 0, 10),
    ("CapControls_Get_DeadTime", 0, 10),
    ("CapControls_Get_Delay", 0, 10),
    ("CapControls_Get_DelayOff", 0, 10),
    ("CapControls_Get_OFFSetting", 0, 10),
    ("CapControls_Get_ONSetting", 0, 10),
    ("CapControls_Get_PTratio", 0, 10),
    ("CapControls_Get_Vmax", 0, 10),
    ("CapControls_Get_Vmin", 0, 10),
    ("CktElement_Get_EmergAmps", 0, 10),
    ("CktElement_Get_NormalAmps", 0, 10),
    ("CktElement_Get_VariableValue", 0, 10),
    ("Fuses_Get_RatedCurrent", 0, 10),
    ("Fuses_Get_Delay", 0, 10),
    ("Generators_Get_kV", 0, 10),
    ("Generators_Get_kvar", 0, 10),
    ("Generators_Get_kW", 0, 10),
    ("Generators_Get_PF", 0, 10),
    ("Generators_Get_kVArated", 0, 10),
    ("Generators_Get_Vmaxpu", 0, 10),
    ("Generators_Get_Vminpu", 0, 10),
    ("Generators_Get_kva", 0, 10),
    ("GICSources_Get_EN", 0, 10),
    ("GICSources_Get_EE", 0, 10),
    ("GICSources_Get_Lat1", 0, 10),
    ("GICSources_Get_Lat2", 0, 10),
    ("GICSources_Get_Lon1", 0, 10),
    ("GICSources_Get_Lon2", 0, 10),
    ("GICSources_Get_Volts", 0, 10),
    ("ISources_Get_Amps", 0, 10),
    ("ISources_Get_AngleDeg", 0, 10),
    ("ISources_Get_Frequency", 0, 10),
    ("LineCodes_Get_R1", 0, 10),
    ("LineCodes_Get_X1", 0, 10),
    ("LineCodes_Get_R0", 0, 10),
    ("LineCodes_Get_X0", 0, 10),
    ("LineCodes_Get_C0", 0, 10),
    ("LineCodes_Get_C1", 0, 10),
    ("LineCodes_Get_NormAmps", 0, 10),
    ("LineCodes_Get_EmergAmps", 0, 10),
    ("Lines_Get_Length", 0, 10),
    ("Lines_Get_R1", 0, 10),
    ("Lines_Get_X1", 0, 10),
    ("Lines_Get_C0", 0, 10),
    ("Lines_Get_C1", 0, 10),
    ("Lines_Get_R0", 0, 10),
    ("Lines_Get_X0", 0, 10),
    ("Lines_Get_EmergAmps", 0, 10),
    ("Lines_Get_NormAmps", 0, 10),
    ("Lines_Get_Rg", 0, 10),
    ("Lines_Get_Rho", 0, 10),
    ("Lines_Get_Xg", 0, 10),
    ("Lines_Get_SeasonRating", 0, 10),
    ("Loads_Get_kV", 0, 10),
    ("Loads_Get_kvar", 0, 10),
    ("Loads_Get_kW", 0, 10),
    ("Loads_Get_PF", 0, 10),
    ("Loads_Get_AllocationFactor", 0, 10),
    ("Loads_Get_Cfactor", 0, 10),
    ("Loads_Get_CVRvars", 0, 10),
    ("Loads_Get_CVRwatts", 0, 10),
    ("Loads_Get_kva", 0, 10),
    ("Loads_Get_kwh", 0, 10),
    ("Loads_Get_kwhdays", 0, 10),
    ("Loads_Get_PctMean", 0, 10),
    ("Loads_Get_PctStdDev", 0, 10),
    ("Loads_Get_Rneut", 0, 10),
    ("Loads_Get_Vmaxpu", 0, 10),
    ("Loads_Get_Vminemerg", 0, 10),
    ("Loads_Get_Vminnorm", 0, 10),
    ("Loads_Get_Vminpu", 0, 10),
    ("Loads_Get_xfkVA", 0, 10),
    ("Loads_Get_Xneut", 0, 10),
    ("Loads_Get_pctSeriesRL", 0, 10),
    ("Loads_Get_RelWeight", 0, 10),
    ("LoadShapes_Get_HrInterval", 0, 10),
    ("LoadShapes_Get_MinInterval", 0, 10),
    ("LoadShapes_Get_SInterval", 0, 10),
    ("LoadShapes_Get_PBase", 0, 10),
    ("LoadShapes_Get_Qbase", 0, 10),
    ("Meters_Get_SAIFI", 0, 10),
    ("Meters_Get_SAIFIKW", 0, 10),
    ("Meters_Get_SAIDI", 0, 10),
    ("Meters_Get_CustInterrupts", 0, 10),
    ("Meters_Get_AvgRepairTime", 0, 10),
    ("Meters_Get_FaultRateXRepairHrs", 0, 10),
    ("Meters_Get_SumBranchFltRates", 0, 10),
    ("Parser_Get_DblValue", 0, 10),
    ("PDElements_Get_FaultRate", 0, 10),
    ("PDElements_Get_pctPermanent", 0, 10),
    ("PDElements_Get_AccumulatedL", 0, 10),
    ("PDElements_Get_Lambda", 0, 10),
    ("PDElements_Get_RepairTime", 0, 10),
    ("PDElements_Get_TotalMiles", 0, 10),
    ("PVSystems_Get_Irradiance", 0, 10),
    ("PVSystems_Get_kvar", 0, 10),
    ("PVSystems_Get_kVArated", 0, 10),
    ("PVSystems_Get_kW", 0, 10),
    ("PVSystems_Get_PF", 0, 10),
    ("PVSystems_Get_Pmpp", 0, 10),
    ("PVSystems_Get_IrradianceNow", 0, 10),
    ("Reclosers_Get_PhaseTrip", 0, 10),
    ("Reclosers_Get_GroundInst", 0, 10),
    ("Reclosers_Get_GroundTrip", 0, 10),
    ("Reclosers_Get_PhaseInst", 0, 10),
    ("RegControls_Get_CTPrimary", 0, 10),
    ("RegControls_Get_Delay", 0, 10),
    ("RegControls_Get_ForwardBand", 0, 10),
    ("RegControls_Get_ForwardR", 0, 10),
    ("RegControls_Get_ForwardVreg", 0, 10),
    ("RegControls_Get_ForwardX", 0, 10),
    ("RegControls_Get_PTratio", 0, 10),
    ("RegControls_Get_ReverseBand", 0, 10),
    ("RegControls_Get_ReverseR", 0, 10),
    ("RegControls_Get_ReverseVreg", 0, 10),
    ("RegControls_Get_ReverseX", 0, 10),
    ("RegControls_Get_TapDelay", 0, 10),
    ("RegControls_Get_VoltageLimit", 0, 10),
    ("Sensors_Get_PctError", 0, 10),
    ("Sensors_Get_Weight", 0, 10),
    ("Sensors_Get_kVbase", 0, 10),
    ("Settings_Get_EmergVmaxpu", 0, 10),
    ("Settings_Get_EmergVminpu", 0, 10),
    ("Settings_Get_NormVmaxpu", 0, 10),
    ("Settings_Get_NormVminpu", 0, 10),
    ("Settings_Get_LossWeight", 0, 10),
    ("Settings_Get_UEweight", 0, 10),
    ("Settings_Get_PriceSignal", 0, 10),
    ("Solution_Get_Frequency", 0, 10),
    ("Solution_Get_LoadMult", 0, 10),
    ("Solution_Get_Seconds", 0, 10),
    ("Solution_Get_StepSize", 0, 10),
    ("Solution_Get_Tolerance", 0, 10),
    ("Solution_Get_pctGrowth", 0, 10),
    ("Solution_Get_GenkW", 0, 10),
    ("Solution_Get_GenPF", 0, 10),
    ("Solution_Get_Capkvar", 0, 10),
    ("Solution_Get_GenMult", 0, 10),
    ("Solution_Get_dblHour", 0, 10),
    ("Solution_Get_Process_Time", 0, 10),
    ("Solution_Get_Total_Time", 0, 10),
    ("Solution_Get_Time_of_Step", 0, 10),
    ("Solution_Get_IntervalHrs", 0, 10),
    ("SwtControls_Get_Delay", 0, 10),
    ("Transformers_Get_kV", 0, 10),
    ("Transformers_Get_kVA", 0, 10),
    ("Transformers_Get_MaxTap", 0, 10),
    ("Transformers_Get_MinTap", 0, 10),
    ("Transformers_Get_R", 0, 10),
    ("Transformers_Get_Rneut", 0, 10),
    ("Transformers_Get_Tap", 0, 10),
    ("Transformers_Get_Xhl", 0, 10),
    ("Transformers_Get_Xht", 0, 10),
    ("Transformers_Get_Xlt", 0, 10),
    ("Transformers_Get_Xneut", 0, 10),
    ("Transformers_Get_RdcOhms", 0, 10),
    ("Vsources_Get_BasekV", 0, 10),
    ("Vsources_Get_pu", 0, 10),
    ("Vsources_Get_AngleDeg", 0, 10),
    ("Vsources_Get_Frequency", 0, 10),
    ("XYCurves_Get_x", 0, 10),
    ("XYCurves_Get_y", 0, 10),
    ("XYCurves_Get_Xscale", 0, 10),
    ("XYCurves_Get_Xshift", 0, 10),
    ("XYCurves_Get_Yscale", 0, 10),
    ("XYCurves_Get_Yshift", 0, 10),
    ("ReduceCkt_Get_Zmag", 0, 10),
    ("Storages_Get_puSOC", 0, 10),
    ("Storages_Get_AmpLimit", 0, 10),
    ("Storages_Get_AmpLimitGain", 0, 10),
    ("Storages_Get_ChargeTrigger", 0, 10),
    ("Storages_Get_DischargeTrigger", 0, 10),
    ("Storages_Get_EffCharge", 0, 10),
    ("Storages_Get_EffDischarge", 0, 10),
    ("Storages_Get_Kp", 0, 10),
    ("Storages_Get_kV", 0, 10),
    ("Storages_Get_kVA", 0, 10),
    ("Storages_Get_kvar", 0, 10),
    ("Storages_Get_kVDC", 0, 10),
    ("Storages_Get_kW", 0, 10),
    ("Storages_Get_kWhRated", 0, 10),
    ("Storages_Get_kWRated", 0, 10),
    ("Storages_Get_PF", 0, 10),
    ("Storages_Get_PITol", 0, 10),
    ("Storages_Get_SafeVoltage", 0, 10),
    ("Storages_Get_TimeChargeTrig", 0, 10),
    ("CNData_Get_Rdc", 0, 10),
    ("CNData_Get_Rac", 0, 10),
    ("CNData_Get_GMRac", 0, 10),
    ("CNData_Get_Radius", 0, 10),
    ("CNData_Get_Diameter", 0, 10),
    ("CNData_Get_NormAmps", 0, 10),
    ("CNData_Get_EmergAmps", 0, 10),
    ("CNData_Get_EpsR", 0, 10),
    ("CNData_Get_InsLayer", 0, 10),
    ("CNData_Get_DiaIns", 0, 10),
    ("CNData_Get_DiaCable", 0, 10),
    ("CNData_Get_DiaStrand", 0, 10),
    ("CNData_Get_GmrStrand", 0, 10),
    ("CNData_Get_RStrand", 0, 10),
    ("LineGeometries_Get_RhoEarth", 0, 10),
    ("LineGeometries_Get_NormAmps", 0, 10),
    ("LineGeometries_Get_EmergAmps", 0, 10),
    ("Reactors_Get_kV", 0, 10),
    ("Reactors_Get_kvar", 0, 10),
    ("Reactors_Get_LmH", 0, 10),
    ("Reactors_Get_R", 0, 10),
    ("Reactors_Get_X", 0, 10),
    ("Reactors_Get_Rp", 0, 10),
    ("TSData_Get_Rdc", 0, 10),
    ("TSData_Get_Rac", 0, 10),
    ("TSData_Get_GMRac", 0, 10),
    ("TSData_Get_Radius", 0, 10),
    ("TSData_Get_Diameter", 0, 10),
    ("TSData_Get_NormAmps", 0, 10),
    ("TSData_Get_EmergAmps", 0, 10),
    ("TSData_Get_EpsR", 0, 10),
    ("TSData_Get_InsLayer", 0, 10),
    ("TSData_Get_DiaIns", 0, 10),
    ("TSData_Get_DiaCable", 0, 10),
    ("TSData_Get_DiaShield", 0, 10),
    ("TSData_Get_TapeLayer", 0, 10),
    ("TSData_Get_TapeLap", 0, 10),
    ("WireData_Get_Rdc", 0, 10),
    ("WireData_Get_Rac", 0, 10),
    ("WireData_Get_GMRac", 0, 10),
    ("WireData_Get_Radius", 0, 10),
    ("WireData_Get_Diameter", 0, 10),
    ("WireData_Get_NormAmps", 0, 10),
    ("WireData_Get_EmergAmps", 0, 10),
    ("WireData_Get_CapRadius", 0, 10),
    ("LoadShapes_Get_MaxP", 0, 10),
    ("LoadShapes_Get_MaxQ", 0, 10),
    ("WindGens_Get_kV", 0, 10),
    ("WindGens_Get_kvar", 0, 10),
    ("WindGens_Get_kW", 0, 10),
    ("WindGens_Get_PF", 0, 10),
    ("WindGens_Get_kVA", 0, 10),
    ("WindGens_Get_Ag", 0, 10),
    ("WindGens_Get_Cp", 0, 10),
    ("WindGens_Get_Lamda", 0, 10),
    ("WindGens_Get_pd", 0, 10),
    ("WindGens_Get_PSS", 0, 10),
    ("WindGens_Get_QSS", 0, 10),
    ("WindGens_Get_Rad", 0, 10),
    ("WindGens_Get_RThev", 0, 10),
    ("WindGens_Get_VCutIn", 0, 10),
    ("WindGens_Get_VCutOut", 0, 10),
    ("WindGens_Get_Vss", 0, 10),
    ("WindGens_Get_WindSpeed", 0, 10),
    ("WindGens_Get_XThev", 0, 10),
)

bool_funcs = (
    ("Bus_ZscRefresh", 0, 11),
    ("Bus_Get_Coorddefined", 0, 11),
    ("Capacitors_Get_IsDelta", 0, 11),
    ("Capacitors_AddStep", 0, 11),
    ("Capacitors_SubtractStep", 0, 11),
    ("CapControls_Get_UseVoltOverride", 0, 11),
    ("CktElement_Get_Enabled", 0, 11),
    ("CktElement_Get_HasVoltControl", 0, 11),
    ("CktElement_Get_HasSwitchControl", 0, 11),
    ("CktElement_Get_HasOCPDevice", 0, 11),
    ("CktElement_Get_IsIsolated", 0, 11),
    ("DSS_Get_AllowForms", 0, 11),
    ("DSS_Get_AllowEditor", 0, 11),
    ("DSS_Get_LegacyModels", 0, 11),
    ("DSS_Get_AllowDOScmd", 0, 11),
    ("DSS_Get_AllowChangeDir", 0, 11),
    ("DSS_Get_EnableArrayDimensions", 0, 11),
    ("DSS_Get_COMErrorResults", 0, 11),
    ("Fuses_IsBlown", 0, 11),
    ("Generators_Get_ForcedON", 0, 11),
    ("Generators_Get_IsDelta", 0, 11),
    ("LineCodes_Get_IsZ1Z0", 0, 11),
    ("Lines_Get_IsSwitch", 0, 11),
    ("Loads_Get_IsDelta", 0, 11),
    ("LoadShapes_Get_UseActual", 0, 11),
    ("Meters_Get_DIFilesAreOpen", 0, 11),
    ("Parser_Get_AutoIncrement", 0, 11),
    ("PDElements_Get_IsShunt", 0, 11),
    ("RegControls_Get_IsInverseTime", 0, 11),
    ("RegControls_Get_IsReversible", 0, 11),
    ("Sensors_Get_IsDelta", 0, 11),
    ("Sensors_Get_ReverseDelta", 0, 11),
    ("Settings_Get_AllowDuplicates", 0, 11),
    ("Settings_Get_ZoneLock", 0, 11),
    ("Settings_Get_Trapezoidal", 0, 11),
    ("Settings_Get_ControlTrace", 0, 11),
    ("Settings_Get_LoadsTerminalCheck", 0, 11),
    ("Solution_Get_SystemYChanged", 0, 11),
    ("Solution_Get_Converged", 0, 11),
    ("Solution_Get_ControlActionsDone", 0, 11),
    ("SwtControls_Get_IsLocked", 0, 11),
    ("Transformers_Get_IsDelta", 0, 11),
    ("YMatrix_Get_SystemYChanged", 0, 11),
    ("YMatrix_Get_UseAuxCurrents", 0, 11),
    ("ReduceCkt_Get_KeepLoad", 0, 11),
    ("Storages_Get_LimitCurrent", 0, 11),
    ("LineGeometries_Get_Reduce", 0, 11),
    ("Reactors_Get_IsDelta", 0, 11),
    ("Reactors_Get_Parallel", 0, 11),
    ("Error_Get_EarlyAbort", 0, 11),
    ("Error_Get_ExtendedErrors", 0, 11),
    ("WindGens_Get_IsDelta", 0, 11),
    ("YMatrix_CheckConvergence", 0, 11),
    ("YMatrix_Get_LoadsNeedUpdating", 0, 11),
    ("YMatrix_Get_SolutionInitialized", 0, 11),
)

